# Generated by Django 2.0 on 2019-06-12 05:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia_admin', '0003_auto_20190518_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_admin',
            name='Comentario',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia_admin',
            name='Dia2',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('Domingo', 'Domingo'), ('.', '')], default='.', help_text='En el caso de que solo sea un dia deje vacio este campo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materia_admin',
            name='hora',
            field=models.CharField(help_text='El formato de la hora tiene que ser como el siguiente ejemplo si son dos dias 12:45pm/4:50pm  o si es un solo dia debe indicar la hora de inicio y la hora de finalizacion 12:45pm a 1:30pm', max_length=50),
        ),
    ]
